[feat] support k3s install

diff --git a/bin/install-k8s b/bin/install-k8s
--- a/bin/install-k8s
+++ b/bin/install-k8s
@@ -1,4 +1,13 @@
 #!/bin/sh
 
-ansible-playbook -i /opt/out/hosts/ansible_hosts /opt/nautes/wait-for-host-ready.yaml
-ansible-playbook -i /opt/out/hosts/ansible_hosts /opt/kubespray/cluster.yml
+set -x
+KUBERNETES_TYPE=$(yq '.deploy.kubernetes.type' /opt/vars.yaml)
+
+if [ $KUBERNETES_TYPE = "k8s" ]; then
+  ansible-playbook -i /opt/out/hosts/ansible_hosts /opt/kubespray/cluster.yml
+elif [ $KUBERNETES_TYPE = "k3s"  ]; then
+  ansible-playbook -i /opt/out/hosts/ansible_hosts -e @/opt/vars.yaml /opt/nautes/k3s.yaml
+else
+  echo "Error: Unknow kubernetes type"
+  exit 1
+fi
